### ISSUE TITLE
Should clear the screen

### ISSUE THREAD

**Issue by thistehneisen** [Randpy/PythonBattleshipGame#2]
Else the other player, upon a bigger terminal window, can see where the ships have been placed.

Also, sh: cls: command not found

**Comment by JorritWillaert** [comment]
Dear, 

First of all, thanks for helping me!
When playing the game in 'Windows Powershell', the screen gets cleared properly every time. This because of the cls command. 
I guess your playing in the standard command prompt of Windows? 
Do you know how we could make that the cls command works in Powershell and in the standard command prompt?

Thanks in advance!
Randpy

**Comment by thistehneisen** [comment]
Hi there,

Actually I was trying it on OS X, iTerm (bash), so I guess you have to check whether "cls" command exists, and if not, use "clear".

**Comment by JorritWillaert** [comment]
Found the problem:
`os.system('cls')  # For Windows`
`os.system('clear')  # For Linux/OS X`

A solution that works for all operating systems is certainly welcome!
